# Change these first
owner: ShinyColorsWiki # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Wiki Main Page
    url: https://shinycolors.wiki/wiki/Main_Page

  - name: "Wiki Page: [Card List/Produce](https://shinycolors.wiki/wiki/Card_List/Produce)"
    url: https://shinycolors.wiki/wiki/Card_List/Produce
    maxResponseTime: 45000
  - name: "Wiki Page: [Card List/Support](https://shinycolors.wiki/wiki/Card_List/Support)"
    url: https://shinycolors.wiki/wiki/Card_List/Support
    maxResponseTime: 45000
  - name: "Wiki Page: [Gacha/Previous Gacha Banners](https://shinycolors.wiki/wiki/Gacha/Previous_Gacha_Banners)"
    url: https://shinycolors.wiki/wiki/Gacha/Previous_Gacha_Banners
    maxResponseTime: 45000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.shinycolors.wiki
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wiki Status
  introTitle: "**ShinyColors.wiki** status"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime) and GitHub.
  navbar:
    - title: Status
      href: /
    - title: Wiki
      href: https://shinycolors.wiki/wiki/Main_Page

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
